apiVersion: v1
kind: Pod
metadata:
  name: init-wait-db
  labels:
    app: db-waiter
spec:
  containers:
  - name: app
    image: nginx
  initContainers:
  - name: wait-for-db
    image: busybox
    command: ['sh', '-c', 'until nc -z db-service 5432; do echo waiting for db; sleep 2; done;']
