apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name              tail
        Path              /var/log/nginx/access.log
        Path_Key          log_path
        Tag               nginx-logs
        Refresh_Interval  5
        DB                /var/log/flb_nginx.db
        DB.Sync           Normal

    [FILTER]
        Name modify
        Match nginx-logs
        Add  app_name ${APP_NAME}

    [OUTPUT]
        Name              azure
        Match             nginx-logs
        Customer_ID       ${WORKSPACE_ID}
        Shared_Key        ${SHARED_KEY}
        Log_Type          nginxlogs

