---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-tomcat
spec:
  containers:
    - name: tomcat
      image: tomcat:9.0
      ports:
        - containerPort: 8080
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-tomcat-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tomcat-svc
spec:
  selector:
    app: nginx-tomcat
  ports:
    - protocol: TCP
      port: 80       # External port (what users hit)
      targetPort: 80 # Container port in NGINX
  type: LoadBalancer
